version: "3.8"

services:
  database:
    image: postgres
    container_name: enjoy_life_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./init/init_database.sql:/docker-entrypoint-initdb.d/init.sql

  elasticsearch:
    image: elasticsearch:7.17.5
    container_name: enjoy_life_elasticsearch
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - elastic:/usr/share/elasticsearch/data

  kibana:
    image: kibana:7.17.5
    container_name: enjoy_life_kibana
    environment:
      SERVER_NAME: 0.0.0.0:5601
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  db_volume:
  elastic: