version: "3.8"

services:
  database:
    image: postgres
    container_name: enjoy_life_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./init/init_database.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_volume: